(()=>{'use strict';
const $=id=>document.getElementById(id),groups=['Typed, single-language','Typed, code-switched','Speech, clean audio','Speech, noisy audio'];
const percent=(x,d=1)=>(100*x).toFixed(d)+'%';
function wilson(k,n){const z=1.959963984540054,p=k/n,den=1+z*z/n,centre=(p+z*z/(2*n))/den,half=z*Math.sqrt(p*(1-p)/n+z*z/(4*n*n))/den;return[centre-half,centre+half];}
function renderAudit(){
 const balanced=$('audit-design').value==='balanced',n=balanced?[40,40,40,40]:[120,20,16,4],k=balanced?[36,28,35,20]:[108,14,14,2],mix=[.4,.2,.2,.2];
 $('audit-rows').innerHTML=groups.map((g,i)=>{const ci=wilson(k[i],n[i]);return `<tr><th scope="row">${g}</th><td>${k[i]} / ${n[i]}</td><td>${percent(k[i]/n[i])}</td><td><span class="interval-track" aria-hidden="true"><span class="interval-range" style="left:${ci[0]*100}%;width:${(ci[1]-ci[0])*100}%"></span><span class="interval-point" style="left:${k[i]/n[i]*100}%"></span></span>${percent(ci[0])}–${percent(ci[1])}</td></tr>`}).join('');
 $('audit-raw').textContent=percent(k.reduce((a,b)=>a+b)/160);$('audit-weighted').textContent=percent(k.reduce((a,b,i)=>a+mix[i]*b/n[i],0));
 $('audit-status').textContent=balanced?'The raw average is lower because the audit mix changed. Every context’s pass rate is unchanged. Forty noisy-speech reviews narrow its interval.':'Only four noisy-speech cases support the last estimate. Their interval is wide, even though the raw audit average looks strong.';
}
const cases=[{s:.98,g:0,ok:true},{s:.97,g:0,ok:true},{s:.96,g:2,ok:false},{s:.94,g:0,ok:true},{s:.91,g:1,ok:true},{s:.88,g:1,ok:false},{s:.86,g:1,ok:true},{s:.83,g:2,ok:true},{s:.78,g:3,ok:false},{s:.74,g:2,ok:true},{s:.68,g:3,ok:false},{s:.55,g:3,ok:true}];
function renderDecisions(){
 const t=Number($('answer-threshold').value),released=cases.filter(c=>c.s>=t),wrong=released.filter(c=>!c.ok),withheld=cases.filter(c=>c.ok&&c.s<t);
 $('threshold-value').textContent=t.toFixed(2);$('answer-coverage').textContent=`${released.length} / ${cases.length}`;$('answer-error').textContent=released.length?`${wrong.length} / ${released.length} (${percent(wrong.length/released.length)})`:'Undefined (no answers)';$('answer-deferred').textContent=withheld.length;
 $('context-coverage').innerHTML=groups.map((g,i)=>{const count=released.filter(c=>c.g===i).length;return `<div>${g}<strong>${count} / 3 answered</strong><div class="coverage-track"><span style="width:${count/3*100}%"></span></div></div>`}).join('');
 $('decision-rows').innerHTML=cases.map((c,i)=>`<tr><th scope="row">V${i+1}</th><td>${groups[c.g]}</td><td>${c.s.toFixed(2)}</td><td>${c.ok?'Supported':'Unsupported'}</td><td>${c.s>=t?'Answer':'Defer'}</td></tr>`).join('');
 $('decision-status').textContent=!released.length?'No answers are released. This avoids releasing these drafts but provides no direct answers; the error rate among answers is undefined.':`${released.length} drafts are released; ${wrong.length} are unsupported. ${withheld.length} supported drafts are deferred. A high score can still be wrong. Check who receives answers, not only the aggregate error fraction.`;
}
const candidates=[
 {id:'T1',g:0,title:'A registration deadline',cost:2,value:.82},{id:'T2',g:0,title:'Two course names',cost:2,value:.78},{id:'T3',g:0,title:'A short opening-hours query',cost:1,value:.70},
 {id:'M1',g:1,title:'A mixed-language date question',cost:2,value:.98},{id:'M2',g:1,title:'A second date phrasing',cost:2,value:.94},{id:'M3',g:1,title:'A related registration query',cost:2,value:.90},
 {id:'C1',g:2,title:'A spoken course nickname',cost:3,value:.60},{id:'C2',g:2,title:'A clear spoken time',cost:2,value:.52},{id:'C3',g:2,title:'A spoken follow-up',cost:2,value:.42},
 {id:'N1',g:3,title:'A date masked by background noise',cost:4,value:.64},{id:'N2',g:3,title:'A long interrupted recording',cost:3,value:.58},{id:'N3',g:3,title:'A short unclear recording',cost:2,value:.50}];
function selectBatch(rule,budget){
 if(rule==='random'){let ids=candidates.map((_,i)=>i),state=2026;for(let i=ids.length-1;i>0;i--){state=(Math.imul(1664525,state)+1013904223)>>>0;let j=Math.floor((state/4294967296)*(i+1));[ids[i],ids[j]]=[ids[j],ids[i]];}let chosen=[],cost=0;for(const id of ids)if(cost+candidates[id].cost<=budget){chosen.push(id);cost+=candidates[id].cost;}return chosen;}
 let best=null,bestValue=-1,bestCost=Infinity;
 for(let mask=0;mask<(1<<candidates.length);mask++){let cost=0,value=0,coverage=0,ids=[];for(let i=0;i<candidates.length;i++)if(mask&(1<<i)){let c=candidates[i];cost+=c.cost;value+=c.value;coverage|=1<<c.g;ids.push(i);}if(cost>budget||(rule==='coverage'&&coverage!==15))continue;if(value>bestValue+1e-9||(Math.abs(value-bestValue)<1e-9&&cost<bestCost)){best=ids;bestValue=value;bestCost=cost;}}
 return best;
}
function drawCandidates(selected=[]){$('annotation-cards').innerHTML=candidates.map((c,i)=>`<article class="candidate${selected.includes(i)?' selected':''}"><span class="candidate-id">${c.id} / ${groups[c.g]}</span><h4>${c.title}</h4><div class="candidate-numbers"><span>Value ${c.value.toFixed(2)}</span><span>${c.cost} min</span></div><span class="selection-label">${selected.includes(i)?'Selected for review':'Not selected'}</span></article>`).join('');}
function pendingSelection(){drawCandidates();$('selection-metrics').hidden=true;$('selection-status').textContent='Selection settings changed. Select a batch to apply them.';$('budget-value').textContent=$('annotation-budget').value;}
function renderSelection(){
 const budget=Number($('annotation-budget').value),rule=$('annotation-strategy').value,selected=selectBatch(rule,budget);drawCandidates(selected||[]);
 if(selected===null){$('selection-metrics').hidden=true;$('selection-status').textContent=`No feasible batch: covering all four contexts requires at least 7 minutes, but the budget is ${budget}. Increase the budget or explicitly reconsider the requirement.`;return;}
 const items=selected.map(i=>candidates[i]),cost=items.reduce((a,c)=>a+c.cost,0),value=items.reduce((a,c)=>a+c.value,0),covered=new Set(items.map(c=>c.g));
 $('selection-metrics').hidden=false;$('selection-metrics').innerHTML=`<div><span>Review time</span><strong>${cost} / ${budget} min</strong><small>${items.length} candidates selected</small></div><div><span>Total acquisition value</span><strong>${value.toFixed(2)}</strong><small>Illustrative score, not learning gain</small></div><div><span>Contexts represented</span><strong>${covered.size} / 4</strong><small>Coarse coverage, not subgroup assurance</small></div>`;
 $('selection-status').textContent=`Selected ${items.map(c=>c.id).join(', ')}. ${covered.size===4?'All four contexts are represented.':`Missing: ${groups.filter((_,i)=>!covered.has(i)).join('; ')}.`} Human review and a model update would come next; neither is simulated here.`;
}
document.querySelectorAll('[data-lab]').forEach(el=>el.disabled=false);
$('audit-design').addEventListener('change',renderAudit);$('audit-reset').addEventListener('click',()=>{$('audit-design').value='convenience';renderAudit();});
$('answer-threshold').addEventListener('input',renderDecisions);$('decision-reset').addEventListener('click',()=>{$('answer-threshold').value='.80';renderDecisions();});
$('reveal-evidence').addEventListener('click',()=>{const open=$('evidence-answer').hidden;$('evidence-answer').hidden=!open;$('reveal-evidence').setAttribute('aria-expanded',String(open));$('reveal-evidence').textContent=open?'Hide the source and review':'Reveal the source and review';});
$('annotation-strategy').addEventListener('change',pendingSelection);$('annotation-budget').addEventListener('input',pendingSelection);$('select-batch').addEventListener('click',renderSelection);$('annotation-reset').addEventListener('click',()=>{$('annotation-strategy').value='value';$('annotation-budget').value='12';$('budget-value').textContent='12';drawCandidates();$('selection-metrics').hidden=true;$('selection-status').textContent='Choose a rule and select a batch. Labels have not been collected.';});
renderAudit();renderDecisions();drawCandidates();
const reduced=matchMedia('(prefers-reduced-motion: reduce)'),steps=[...document.querySelectorAll('.evidence-steps>div')],motion=$('motion-toggle');let timer=null,index=0,playing=!reduced.matches;
const heroFrames=[['draft','Generated draft','“Yes, you can register on Friday.”','The sentence is fluent. Its deadline contradicts the notice.'],['check','Source check','Friday is after the Thursday deadline.','The class date is correct. The registration claim is unsupported.'],['correct','Corrected response','“Registration closes Thursday at 17:00.”','Friday would be too late for the Saturday class.']];
function paintMotion(){steps.forEach((el,i)=>el.classList.toggle('current',i===index));const f=heroFrames[index];$('hero-response').dataset.state=f[0];$('hero-label').textContent=f[1];$('hero-draft').textContent=f[2];$('hero-check').textContent=f[3];}
function setMotion(play){playing=play;clearInterval(timer);timer=null;if(play)timer=setInterval(()=>{index=(index+1)%steps.length;paintMotion();},5200);motion.textContent=play?'Pause animation':'Play animation';motion.setAttribute('aria-pressed',String(play));}
motion.hidden=false;paintMotion();setMotion(playing);motion.addEventListener('click',()=>setMotion(!playing));reduced.addEventListener('change',e=>{if(e.matches)setMotion(false);});
// The walkthrough is authored, not a model simulation. Each branch changes the evidence and remedy.
const frame=(heading,leftLabel,left,tokens,rightLabel,right,verdict,explanation)=>({heading,leftLabel,left,tokens,rightLabel,right,verdict,explanation});
const commonInput=frame('Keep the two dates distinct.','Question','Can I register on Friday for the Saturday class?',['Friday: registration?','Saturday: class'],'Meaning to preserve','The person asks about registering, not about when the class starts.','Check intent and dates','A transcription or translation can change a crucial date before answer generation begins.');
const currentNotice=frame('Retrieve the notice for this class.','Current notice','Registration closes Thursday at 17:00. The class begins Saturday at 09:00.',['Thursday: deadline','Saturday: class'],'Source check','Confirm the course, registration period, and notice version before using this passage.','Relevant and current in this example','Grounding requires the right document. A citation to another course or an expired notice would not settle this question.');
const finalAudit=frame('Test the correction on independent cases.','Held-out evaluation','Review new questions across input types and the language varieties the service claims to support.',['Accuracy','Answer coverage','Review effort'],'Deployment decision','Report counts and uncertainty. Check whether fewer errors came with excessive deferral for some groups.','No improvement is assumed','The walkthrough ends with a test to perform, not a claimed gain. The audit lab below shows why the distribution of those cases matters.');
const loopFrames={
claim:[commonInput,currentNotice,
frame('A correct source can still produce a wrong answer.','Generated draft','Yes, you can register on Friday. The class begins Saturday at 09:00.',['!Friday: unsupported','Saturday: supported'],'Claim-level comparison','The draft repeats the class time correctly but contradicts the registration deadline.','One supported clause does not validate the answer','This isolates a generation failure: the input and source are available, yet the answer does not follow them.'),
frame('Correct the answer before release.','Verified source fact','Registration closes Thursday at 17:00.',['Thursday: deadline'],'Response to the person','No. Registration closes Thursday at 17:00, so Friday would be too late for the Saturday class.','Answer with the relevant evidence','A source-grounded correction is possible here. If the source check were unresolved, the system should defer instead.'),
frame('Turn the failure into targeted supervision.','Reviewer judgment','The Friday permission contradicts the notice. The class time is supported.',['Unsupported claim label','Corrected response'],'Learning decision','Add this case to the candidate pool with its review cost. Select related failures if they add useful evidence.','Annotate the failure, then test an update','Active learning selects reviews across a pool. It does not mean training on every interaction or treating an automatic critique as ground truth.'),finalAudit],
audio:[
frame('Resolve the day before answering.','Possible transcriptions','Can I register on Friday? / Can I register on Thursday?',['!Friday?','!Thursday?'],'Input uncertainty','The day is unclear in this hypothetical recording. The alternatives imply different answers.','Meaning is unresolved','The uncertainty is in the input. The user should not have to change a legitimate accent or language variety to receive service.'),
frame('The notice cannot tell you what was said.','Current notice','Registration closes Thursday at 17:00. The class begins Saturday at 09:00.',['Thursday: deadline'],'What remains unknown','The source gives a deadline, but it does not resolve whether the person asked about Thursday or Friday.','Clear source, ambiguous question','Retrieval and transcription are different evidence checks. Success at one does not remove uncertainty in the other.'),
frame('A guess at the transcript becomes a confident error.','Draft based on Thursday','Yes, you can register before 17:00 on Thursday.',['!Assumed: Thursday'],'Unresolved interpretation','This would not answer a question about Friday correctly. A fluent draft hides the transcription choice.','Do not release a guessed interpretation','High confidence from the answer generator can coexist with uncertainty earlier in the pipeline.'),
frame('Ask a focused clarification.','Information needed','Which day does the person intend to register?',['Friday or Thursday?'],'Response to the person','Did you mean registering on Thursday or Friday? The notice says registration closes Thursday at 17:00.','Clarify the consequential detail','Offer the clarification in a usable language and format, with a text or staff option if another recording would be difficult.'),
frame('Review the speech error with qualified speakers.','Annotation request','Check the intended day against the recording and conversation. Record ambiguity if it cannot be resolved.',['Verified transcript','Ambiguity label'],'Learning decision','Consider informative speech cases for adaptation. Request better audio when the recording itself is insufficient.','Separate missing experience from missing signal','Language expertise is needed to distinguish a model weakness, a valid local expression, and an irrecoverable recording.'),finalAudit],
source:[commonInput,
frame('A retrieved notice may be out of date.','Retrieved notice','Last term: registration closes Friday at 17:00.',['!Previous term','Friday: old deadline'],'Source check','The current registration policy is absent from the available documents.','Current fact is missing','The relevant test is whether the notice applies now, not whether the retriever found matching words.'),
frame('A citation can support the wrong time period.','Generated draft','Yes, you can register on Friday, according to the registration notice.',['!Expired source'],'Evidence limitation','The draft follows last term’s notice. That does not establish this term’s deadline.','Citation present, current support absent','Textual agreement with a document is insufficient when its scope or validity period does not match the question.'),
frame('State the missing fact and offer a next step.','Evidence available','Only last term’s registration notice is available.',['Current deadline: unknown'],'Response to the person','I cannot confirm this term’s deadline from the notice available. Please check with the centre before planning to register on Friday.','Defer the fact to a current source','In an actual service, provide the centre’s verified contact route. Do not invent a contact or a new deadline.'),
frame('Correct the source collection first.','Staff review','Obtain the current notice and record its course, term, and validity.',['Update source','Remove expired match'],'Learning decision','Re-index and test retrieval. Annotate source-validity failures if the retrieval or checking component needs improvement.','A model update is not always the remedy','Active learning can improve a component that misuses sources. It cannot establish a registration policy the centre has not supplied.'),finalAudit]
};
const phaseNames=['Interpret the question','Retrieve the evidence','Inspect the draft','Choose the response','Direct human review','Re-evaluate the system'];
let loopIndex=0,loopTimer=null;
function stopLoop(){clearInterval(loopTimer);loopTimer=null;$('loop-play').textContent='Play walkthrough';$('loop-play').setAttribute('aria-pressed','false');}
function renderLoop(){const f=loopFrames[$('loop-scenario').value][loopIndex];$('loop-phase').textContent=`0${loopIndex+1} / ${phaseNames[loopIndex]}`;
for(const [id,key]of [['loop-heading','heading'],['loop-left-label','leftLabel'],['loop-left','left'],['loop-right-label','rightLabel'],['loop-right','right'],['loop-verdict','verdict'],['loop-explanation','explanation']])$(id).textContent=f[key];
$('loop-tokens').replaceChildren(...f.tokens.map(value=>{const el=document.createElement('span');el.textContent=value.replace(/^!/,'');if(value.startsWith('!'))el.className='attention';return el;}));
document.querySelectorAll('[data-loop-step]').forEach((b,i)=>{b.setAttribute('aria-pressed',String(i===loopIndex));b.parentElement.classList.toggle('completed',i<loopIndex);});
$('loop-back').disabled=loopIndex===0;$('loop-next').disabled=loopIndex===5;$('loop-progress').textContent=`Step ${loopIndex+1} of 6${loopIndex===5?' · Evaluate before claiming improvement':''}`;
const panel=$('loop-stage');panel.classList.remove('reveal');void panel.offsetWidth;panel.classList.add('reveal');}
function goLoop(i){stopLoop();loopIndex=i;renderLoop();}
document.querySelectorAll('[data-loop-step]').forEach(b=>b.addEventListener('click',()=>goLoop(Number(b.dataset.loopStep))));
$('loop-scenario').addEventListener('change',()=>goLoop(0));$('loop-back').addEventListener('click',()=>goLoop(Math.max(0,loopIndex-1)));$('loop-next').addEventListener('click',()=>goLoop(Math.min(5,loopIndex+1)));$('loop-reset').addEventListener('click',()=>goLoop(0));
$('loop-play').addEventListener('click',()=>{if(loopTimer){stopLoop();return;}if(loopIndex===5){loopIndex=0;renderLoop();}$('loop-play').textContent='Pause walkthrough';$('loop-play').setAttribute('aria-pressed','true');loopTimer=setInterval(()=>{loopIndex++;renderLoop();if(loopIndex===5)stopLoop();},7500);});
reduced.addEventListener('change',e=>{if(e.matches)stopLoop();});document.addEventListener('visibilitychange',()=>{if(document.hidden){stopLoop();setMotion(false);}});renderLoop();stopLoop();
const uncertaintyContent={answer:{heading:'Will this answer be correct and supported?',description:'A fluent Friday answer contradicts the Thursday deadline. Model disagreement or a support score may flag it, but agreement can also be wrong.',remedy:'Check the claim against the current source and correct it before release.',visual:'<span>Friday allowed?</span><span class="uncertainty-link">↓ compare with notice</span><strong>Thursday deadline</strong>'},estimate:{heading:'How precisely has performance been measured?',description:'Two of four noisy-speech cases pass. The observed rate is 50%, but the 95% Wilson interval extends from 15% to 85%. That interval describes sampling uncertainty, not confidence in one answer.',remedy:'Review more representative cases in that context and report the interval. More reviews improve the estimate, not the model itself.',visual:'<span>2 passes / 4 reviews</span><div class="mini-interval"><i></i><b></b></div><strong>15%–85%</strong><span class="uncertainty-link">95% Wilson interval · 0–100% scale</span>'},fact:{heading:'Is the required fact available at all?',description:'Last term’s notice gives a Friday deadline. No current policy is available. Neither an uncertainty score nor more training can establish the new deadline.',remedy:'Obtain a current notice or refer the question to staff. State what is missing instead of guessing.',visual:'<span>Last term’s notice</span><span class="uncertainty-link">↓ validity check</span><strong class="missing-fact">Current deadline missing</strong>'}};
document.querySelectorAll('[data-uncertainty]').forEach(b=>b.addEventListener('click',()=>{const c=uncertaintyContent[b.dataset.uncertainty];document.querySelectorAll('[data-uncertainty]').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));$('uncertainty-heading').textContent=c.heading;$('uncertainty-description').textContent=c.description;$('uncertainty-remedy').replaceChildren(Object.assign(document.createElement('strong'),{textContent:'Next action: '}),document.createTextNode(c.remedy));$('uncertainty-visual').innerHTML=c.visual;}));
})();

(()=>{'use strict';
const $=id=>document.getElementById(id);
document.querySelectorAll('[data-addition]').forEach(el=>el.disabled=false);
$('diacritic-toggle').addEventListener('click',()=>{const stripped=$('diacritic-toggle').getAttribute('aria-pressed')!=='true';$('diacritic-toggle').setAttribute('aria-pressed',String(stripped));$('diacritic-toggle').textContent=stripped?'Restore the diacritics':'Remove the diacritics';document.querySelectorAll('[data-yoruba]').forEach(el=>{el.textContent=stripped?el.dataset.yoruba.normalize('NFD').replace(/\p{M}/gu,''):el.dataset.yoruba;});$('orthography-demo').classList.toggle('stripped',stripped);$('diacritic-status').textContent=stripped?'All three forms are now “owo”. The original meanings remain different; the stripped spelling no longer distinguishes them.':'The written forms preserve distinctions in tone and vowel quality.';});
$('agreement-check').addEventListener('click',()=>{const shown=$('agreement-source').hidden;$('agreement-source').hidden=!shown;$('agreement-check').setAttribute('aria-expanded',String(shown));$('agreement-check').textContent=shown?'Hide the source check':'Check against the current notice';$('agreement-evidence').classList.toggle('contradicted',shown);$('agreement-result').textContent=shown?'0 / 4 supported':'Not checked';$('agreement-caption').textContent=shown?'Every Friday permission contradicts the deadline.':'Agreement does not establish support.';});

// Scores and automatic-answer labels match Experiment 02. Review costs and outcomes are added assumptions.
const reviewCases=[
 {s:.98,g:0,ok:true},{s:.97,g:0,ok:true},{s:.96,g:2,ok:false},{s:.94,g:0,ok:true},
 {s:.91,g:1,ok:true},{s:.88,g:1,ok:false},{s:.86,g:1,ok:true},{s:.83,g:2,ok:true},
 {s:.78,g:3,ok:false},{s:.74,g:2,ok:true},{s:.68,g:3,ok:false},{s:.55,g:3,ok:true}
].map((c,i)=>({...c,id:`V${i+1}`,duration:[6,8,10,14][c.g],resolved:![2,8].includes(i)}));
function renderHandoff(){
 const threshold=Number($('handoff-threshold').value),staff=Number($('handoff-staff').value),windowMinutes=Number($('handoff-window').value),available=Array(staff).fill(0),automatic=[],queue=[];
 for(const c of reviewCases){if(c.s>=threshold){automatic.push(c);continue;}const reviewer=available.indexOf(Math.min(...available)),start=available[reviewer],finish=start+c.duration;available[reviewer]=finish;queue.push({...c,reviewer,start,finish,completed:finish<=windowMinutes});}
 const completed=queue.filter(c=>c.completed),resolved=completed.filter(c=>c.resolved),timely=resolved.filter(c=>c.finish<=30),load=queue.reduce((n,c)=>n+c.duration,0),correctAutomatic=automatic.filter(c=>c.ok).length,wrongAutomatic=automatic.length-correctAutomatic,finishes=completed.map(c=>c.finish).sort((a,b)=>a-b),mid=Math.floor(finishes.length/2),median=!finishes.length?null:finishes.length%2?finishes[mid]:(finishes[mid-1]+finishes[mid])/2;
 $('handoff-threshold-value').textContent=threshold.toFixed(2);$('handoff-load').textContent=`${load} staff-min`;$('handoff-capacity').textContent=`${staff*windowMinutes} staff-min available in this session`;$('handoff-completed').textContent=`${completed.length} / ${queue.length}`;$('handoff-resolved').textContent=`${resolved.length} / ${queue.length}`;$('handoff-delay').textContent=median===null?'Not available':`${median} min`;$('handoff-timely').textContent=`${timely.length} / ${queue.length}`;$('handoff-overall').textContent=`${correctAutomatic+resolved.length} / 12`;
 const pending=queue.length-completed.length,unresolved=completed.length-resolved.length;
 $('handoff-status').textContent=queue.length?`${pending} ${pending===1?'review remains':'reviews remain'} pending at minute ${windowMinutes}. ${unresolved} completed ${unresolved===1?'review does':'reviews do'} not resolve the question. ${wrongAutomatic} unsupported automatic ${wrongAutomatic===1?'answer remains':'answers remain'}. Pending cases are excluded from the median response time.`:`No cases are deferred. Human-response timing is not available. ${wrongAutomatic} unsupported automatic answers remain; ${correctAutomatic} of 12 automatic answers are supported.`;
 $('handoff-timeline').innerHTML=queue.length?`<p class="small">Scheduled review times from arrival · bars share a 0–${windowMinutes} minute scale and stop at the session boundary.</p>`+queue.map(c=>{const start=Math.min(c.start,windowMinutes)/windowMinutes*100,width=Math.max(0,Math.min(c.finish,windowMinutes)-Math.min(c.start,windowMinutes))/windowMinutes*100,state=c.completed?(c.resolved?'Resolved':'Unresolved'):(c.start>=windowMinutes?'Queued':'In progress');return `<div class="review-timeline-row"><strong>${c.id}<small>Reviewer ${c.reviewer+1}</small></strong><div class="review-track" aria-hidden="true"><span class="${c.completed?(c.resolved?'resolved':'unresolved'):'pending'}" style="left:${start}%;width:${width}%"></span></div><span>${c.start}–${c.finish} min<small>${state}</small></span></div>`}).join(''):'<p class="small">The human-review queue is empty at this threshold.</p>';
 $('handoff-rows').innerHTML=reviewCases.map(c=>{const q=queue.find(item=>item.id===c.id);return `<tr><th scope="row">${c.id}</th><td>${q?'Human review':'Automatic'}</td><td>${q?q.start+' min':'Not applicable'}</td><td>${q?q.finish+' min':'Immediate'}</td><td>${q?(q.completed?(q.resolved?'Useful resolution':'Unresolved: missing source fact'):(q.start>=windowMinutes?'Queued':'Review in progress')):(c.ok?'Supported answer':'Unsupported answer')}</td></tr>`}).join('');
}
for(const id of ['handoff-threshold','handoff-staff','handoff-window'])$(id).addEventListener(id==='handoff-threshold'?'input':'change',renderHandoff);
$('handoff-reset').addEventListener('click',()=>{$('handoff-threshold').value='.8';$('handoff-staff').value='1';$('handoff-window').value='60';renderHandoff();});renderHandoff();

const dossiers={
 pilot:{title:'A bounded, supervised pilot',evidence:[['Requested scope','Typed registration questions in one locally reviewed language variety, using current notices; staff supervise the pilot.'],['Independent audit','194 of 200 answers pass. Review of the six failures identifies no critical deadline contradiction in this audit.'],['Human route','18 of 20 referrals resolve the question; 16 of 20 resolve within the locally agreed 30-minute goal.'],['Operating conditions','Staff and speaker representatives accept the observed residual issues for a reversible pilot, with monitoring and a rollback owner. Speech and other varieties are outside the claim.']],responses:{
 pilot:['A limited pilot is defensible under these stated conditions.','The scope matches the evidence, residual failures have been reviewed, and a staffed correction route exists. This supports a monitored pilot, not unrestricted language support.','Keep the scope explicit, monitor failure severity and unresolved referrals, and stop or narrow the pilot if the agreed conditions fail.'],
 evidence:['More evidence could support a more cautious decision.','This may be appropriate if the remaining errors or uncertainty are unacceptable to the people responsible for the service. The current dossier already supplies a basis for a reversible pilot under its stated local agreement.','Specify which unresolved question requires more data, such as performance for another variety or the consequences of the six failures.'],
 repair:['A repair should address an identified failure.','The six failures deserve analysis, but the dossier does not identify a common defective component. An automatic requirement to retrain would go beyond the evidence.','Inspect the failures first. Repair a reproducible mechanism, then test the change independently.']}},
 sparse:{title:'Broad scope, thin speech evidence',evidence:[['Requested scope','Typed and spoken registration questions across several local varieties.'],['Independent audit','Typed, single-language: 90/100 pass. Typed, code-switched: 14/20 pass. Noisy speech: 2/4 pass.'],['What is missing','No variety-level speech breakdown. Four noisy-speech cases cannot establish performance across the requested speech scope.'],['Human route','Referral completion and usefulness for speech users have not been measured.']],responses:{
 pilot:['The requested broad launch exceeds the evidence.','A narrower typed pilot would be a different claim and would still need agreed error tolerance and a measured fallback. The typed score alone cannot justify the speech extension.','Define the narrower scope explicitly and establish its operating conditions before considering a pilot.'],
 evidence:['Collect evidence where the claim is weakest.','Prioritize representative speech cases across the intended varieties, and follow referred users through to resolution. More of the same typed questions would not answer the missing question.','Predefine the sampling plan and rubric with speakers. Keep the resulting final audit separate from tuning.'],
 repair:['Investigate the failures before choosing a component to change.','Two speech failures suggest a problem worth tracing, but this dossier cannot separate transcription, retrieval, and generation. A blanket model update may target the wrong cause.','Review the failed cases and collect representative evidence alongside the diagnosis.']}},
 broken:{title:'A recurring source-selection failure',evidence:[['Requested scope','Registration answers for the current term, using the centre’s notices.'],['Failure investigation','In 17 of 20 targeted Friday queries, retrieval supplies last term’s notice and the answer permits Friday registration.'],['Current evidence','The current notice is available and closes registration on Thursday at 17:00. The version filter is not applied.'],['Limits of this test','These are targeted diagnostic queries, not a representative estimate of deployment error.']],responses:{
 pilot:['The known deadline defect blocks this proposed scope.','A supervised pilot would still expose the specific error unless staff verification prevented those answers from reaching users. That would need to be an explicit, tested intervention.','Repair or isolate the affected path, verify the intervention, and independently re-evaluate before release.'],
 evidence:['More evidence can map the defect, but cannot repair it.','Additional diagnosis may show where else stale notices are selected. It is not a substitute for applying the missing version check.','Repair the source-selection rule and then test on independent cases, including other courses and terms.'],
 repair:['Revise retrieval before another model-training round.','The mechanism is identified: the current notice exists, but retrieval ignores its validity period. Fix and test the version filter, then check whether generation uses the corrected evidence.','Use new held-out questions to measure the full response and verify that the repair introduces no relevant regressions.']}}
};
function renderDossier(){const d=dossiers[$('deployment-dossier').value];$('deployment-evidence').innerHTML=`<h4>${d.title}</h4><dl>${d.evidence.map(([term,value])=>`<dt>${term}</dt><dd>${value}</dd>`).join('')}</dl>`;$('deployment-feedback').hidden=true;$('deployment-feedback').replaceChildren();document.querySelectorAll('[data-deploy-choice]').forEach(b=>b.setAttribute('aria-pressed','false'));}
$('deployment-dossier').addEventListener('change',renderDossier);
document.querySelectorAll('[data-deploy-choice]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-deploy-choice]').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));const [heading,reason,next]=dossiers[$('deployment-dossier').value].responses[b.dataset.deployChoice];$('deployment-feedback').innerHTML=`<h4>${heading}</h4><p>${reason}</p><p><strong>Next evidence or action:</strong> ${next}</p>`;$('deployment-feedback').hidden=false;}));renderDossier();
})();
